[theme]
primaryColor = "#ff9c3c"  # A shade of green, similar to BNP Paribas green
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F1F1F1"  # Light grey for secondary elements
textColor = "#000000"  # Black text
font = "sans serif"  # Optional: Choose a font that matches the brand
